### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by letruxux** [ai-to-ai/Auto-Gmail-Creator#12]
error at "driver is not None": driver referenced before assignment

**Comment by leoshabit** [comment]
Can you indicate the line of error with log message?

Thanks

**Comment by abtinokhovat** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Development/Auto-Gmail-Creator/app.py", line 577, in <module>
    main()
  File "/Users/Development/Auto-Gmail-Creator/app.py", line 573, in main
    if driver is not None:
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by letruxux** [comment]
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/Development/Auto-Gmail-Creator/app.py", line 577, in <module>
>     main()
>   File "/Users/Development/Auto-Gmail-Creator/app.py", line 573, in main
>     if driver is not None:
> UnboundLocalError: local variable 'driver' referenced before assignment

what he said @leoshabit
