### ISSUE TITLE
Error Creating account

### ISSUE THREAD

**Issue by TJLLT** [ai-to-ai/Auto-Gmail-Creator#24]
Perhaps I didn't understand how to use it properly. I simply cloned the repository and tried to execute the code. I began the process of creating an account and everything seemed fine, but after entering the password, Google stated that it wasn't possible to create the account.

**Comment by ai-to-ai** [comment]
Yes. it's probably detected as a bot

If you have any suggestion, feel free to let me know

Thank you

**Comment by TJLLT** [comment]
Do you know how to make it appear as if it's not a bot and create an account?

**Comment by ai-to-ai** [comment]
I am not sure but I guess we can try undetected browser

**Comment by TJLLT** [comment]
You mean by using a different browser? Or are you thinking VPNs? Or Browser Fingerprinting?

**Comment by TJLLT** [comment]
I tried using various extensions, such as Privacy Badger, but nothing worked. If you succeed in doing it, please let me know.

**Comment by ai-to-ai** [comment]
Okay. settled
