### ISSUE TITLE
it wasn't possible to create the account.

### ISSUE THREAD

**Issue by lex0tan** [ai-to-ai/Auto-Gmail-Creator#30]
As other people, i have the same problem after setting the password, i'm using a iproyal socks5 proxy.

**Comment by xD-E-A-T-Hx** [comment]
Read other comments. It explains the reason. You need to customise your chromedriver.exe

**Comment by lex0tan** [comment]
where can i research more on how to customise my driver? :)

**Comment by ai-to-ai** [comment]
@xD-E-A-T-Hx , Thanks for your support. I am still working on it. I know there are lots of people who solved that issue but didn't share
