### ISSUE TITLE
The Script suddenly stopped working.

### ISSUE THREAD

**Issue by Habibullah-pythoner** [ai-to-ai/Auto-Gmail-Creator#34]
It has been a couple of hours since all signups just go to the page below after password section:

Sorry, we could not create your Google Account.

Is anybody else facing the same issue?

**Comment by xD-E-A-T-Hx** [comment]
Check through the other posted issues. This has come up a few times. It's due to the bot detection of google.

**Comment by Habibullah-pythoner** [comment]
No exact solution for this problem, what I did tho was use a function to generate random values from 3 to 8 and use that instead of time.sleep(WAIT), did improve not getting caught, but still I get unlucky.

**Comment by Habibullah-pythoner** [comment]
No exact solution for this problem, what I did tho was use a function to generate random values from 3 to 8 and use that instead of time.sleep(WAIT), did improve not getting caught, but still I get unlucky.

**Comment by Habibullah-pythoner** [comment]
No exact solution for this problem, what I did tho was use a function to generate random values from 3 to 8 and use that instead of time.sleep(WAIT), did improve not getting caught, but still I get unlucky.

**Comment by xD-E-A-T-Hx** [comment]
i run mine on random, its bot detection, are you using selenium with chromedriver or seleniumwire?

**Comment by Habibullah-pythoner** [comment]
I am using the driver that comes with the script, ChromeDriver ig, I tried running undetected_chromedriver but had no success

**Comment by xD-E-A-T-Hx** [comment]
i use rotating chromedriver.exe for mine, i dont use selenium wire etc, this way i have full control and know the files are edited to my specs

the chromedriver has a java marker in it, its the same on all the chromedrivers, so all the google bots have to do is search for this signature and boom, its a bot accessing google, using the rotating driver, i have over 17k different markers so googlebot doesnt know whats a bot and whats a person

**Comment by Habibullah-pythoner** [comment]
you saying your script pass 100% of the time using this method?

**Comment by xD-E-A-T-Hx** [comment]
there are also other factors, like useragents, i have over 1000 that are rotated, proxies, i use paid, public, residential, mobile etc, everything is a factor.  

when i use paid proxies (others are hit and miss), random chromedriver and random useragent, i have had not many errors compared to using normal chromedriver or seleniumwire, im yet to try undetected chromedriver, my biggest problem is phone numbers being accepted.  if they were 100% consistent id be happy

my biggest problem with the rotating chromedriver is, the total size for the files are 209gb

**Comment by Habibullah-pythoner** [comment]
Phone numbers, boy I am dealing with that right now, and it sucks

**Comment by Habibullah-pythoner** [comment]
User agents and ChromeDrivers, am sure you spent a lot of time setting them up, you planning to share or sell them?

**Comment by xD-E-A-T-Hx** [comment]
make sure your proxies match this though, if your using a number from USA and your proxy is in France, it may cause problems. 
im currently randomly rotating between USA and Canada, others are to expensive, yet their success rate i assume would be higher.  it wouldnt imo be beneficial to purchase more expensive numbers

**Comment by xD-E-A-T-Hx** [comment]
> User agents and ChromeDrivers, am sure you spent a lot of time setting them up, you planning to share or sell them?

if i share the useragents, i would be worried, if they are used too much they would get flagged also.
chromedrivers are easy to modify, just takes time(depending on your system) and space like i say, 209gb

**Comment by Habibullah-pythoner** [comment]
Understandable mate

**Comment by xD-E-A-T-Hx** [comment]
sent you an email

**Comment by Habibullah-pythoner** [comment]
> sent you an email

Hey, sorry was out of town for a day.
Haven't received anything in my email, checked spam too

**Comment by Chetan11-dev** [comment]
Hi everyone, to help you bypass Cloudflare-protected websites like https://nowsecure.nl/, I have created an Anti-Detect Library called Botasaurus. Here's how you can use it to visit nowsecure.nl:

1. **Install Botasaurus**
```bash
python -m pip install botasaurus
```

2. **Bypass https://nowsecure.nl/**
```python
from botasaurus import *
from botasaurus.create_stealth_driver import create_stealth_driver

@browser(
    create_driver=create_stealth_driver(
        start_url="https://nowsecure.nl/",
    ),
)
def scrape_heading_task(driver: AntiDetectDriver, data):
    driver.prompt()
    heading = driver.text('h1')
    return heading

scrape_heading_task()    
```

![Now Secure Bypass](https://raw.githubusercontent.com/omkarcloud/botasaurus/master/images/now-secure-bypass.gif)

I suggest learning about bypassing various Cloudflare protections [here.](https://github.com/omkarcloud/botasaurus/tree/master#can-you-bypass-cloudflareimperva-challenges)

## If this has been a lifesaver for you, I would greatly appreciate a [Star here :)](https://github.com/omkarcloud/botasaurus)
